create table if not exists public.pedidos_itens (
  id bigint generated by default as identity not null,
  pedido_id bigint not null references public.pedidos(id) on delete cascade,
  restaurante_id bigint not null references public.restaurantes(id) on delete cascade,
  item_nome text not null,
  item_nome_exibicao text null,
  qtd integer not null default 1,
  preco_unitario numeric null default 0,
  borda text null,
  created_at timestamptz not null default now(),
  constraint pedidos_itens_pkey primary key (id)
);

create index if not exists idx_pedidos_itens_pedido on public.pedidos_itens(pedido_id);
create index if not exists idx_pedidos_itens_restaurante on public.pedidos_itens(restaurante_id);
create index if not exists idx_pedidos_itens_item_nome on public.pedidos_itens(item_nome);
create index if not exists idx_pedidos_itens_borda on public.pedidos_itens(borda);
